package GN.EN.DateTime.behavior;

/*Generated by MPS */


public abstract class AbsoluteTimeConcept_BehaviorDescriptor extends TimeConcept_BehaviorDescriptor {
  public AbsoluteTimeConcept_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.AbsoluteTimeConcept";
  }
}
