package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class AfterInstant_BehaviorDescriptor extends InstantTiming_BehaviorDescriptor {
  public AfterInstant_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.AfterInstant";
  }
}
