package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class BeforeInstant_BehaviorDescriptor extends InstantTiming_BehaviorDescriptor {
  public BeforeInstant_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.BeforeInstant";
  }
}
