package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Before_BehaviorDescriptor extends TemporalExpression_BehaviorDescriptor {
  public Before_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Before";
  }
}
