package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class BeforeInterval_BehaviorDescriptor extends IntervalTiming_BehaviorDescriptor {
  public BeforeInterval_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.BeforeInterval";
  }
}
