package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Between_BehaviorDescriptor extends InstantOperators_BehaviorDescriptor {
  public Between_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Between";
  }
}
