package GN.EN.DateTime.behavior;

/*Generated by MPS */

import GN.EN.behavior.Value_BehaviorDescriptor;

public class DateValue_BehaviorDescriptor extends Value_BehaviorDescriptor {
  public DateValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.DateValue";
  }
}
