package GN.EN.DateTime.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class DateTimeOperands_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DateTimeOperands_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.DateTimeOperands";
  }
}
