package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class DateTime_BehaviorDescriptor extends Instant_BehaviorDescriptor {
  public DateTime_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.DateTime";
  }
}
