package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Days_BehaviorDescriptor extends TimeUnit_BehaviorDescriptor {
  public Days_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Days";
  }
}
