package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Duration_BehaviorDescriptor extends RelativeTimeConcept_BehaviorDescriptor {
  public Duration_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Duration";
  }
}
