package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class During_BehaviorDescriptor extends IntervalTiming_BehaviorDescriptor {
  public During_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.During";
  }
}
