package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Equal_BehaviorDescriptor extends TemporalExpression_BehaviorDescriptor {
  public Equal_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Equal";
  }
}
