package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Friday_BehaviorDescriptor extends DayOfWeek_BehaviorDescriptor {
  public Friday_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Friday";
  }
}
