package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Hours_BehaviorDescriptor extends TimeUnit_BehaviorDescriptor {
  public Hours_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Hours";
  }
}
