package GN.EN.DateTime.behavior;

/*Generated by MPS */


public abstract class InstantOperators_BehaviorDescriptor extends TemporalExpression_BehaviorDescriptor {
  public InstantOperators_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.InstantOperators";
  }
}
