package GN.EN.DateTime.behavior;

/*Generated by MPS */


public abstract class InstantTiming_BehaviorDescriptor extends Timing_BehaviorDescriptor {
  public InstantTiming_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.InstantTiming";
  }
}
