package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class InstantVariable_BehaviorDescriptor extends Instant_BehaviorDescriptor {
  public InstantVariable_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.InstantVariable";
  }
}
