package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class IntervalVariable_BehaviorDescriptor extends Interval_BehaviorDescriptor {
  public IntervalVariable_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.IntervalVariable";
  }
}
