package GN.EN.DateTime.behavior;

/*Generated by MPS */


public abstract class IntervalTiming_BehaviorDescriptor extends Timing_BehaviorDescriptor {
  public IntervalTiming_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.IntervalTiming";
  }
}
