package GN.EN.DateTime.behavior;

/*Generated by MPS */


public abstract class Interval_BehaviorDescriptor extends AbsoluteTimeConcept_BehaviorDescriptor {
  public Interval_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Interval";
  }
}
