package GN.EN.DateTime.behavior;

/*Generated by MPS */


public abstract class IntervalCondition_BehaviorDescriptor extends TimeCondition_BehaviorDescriptor {
  public IntervalCondition_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.IntervalCondition";
  }
}
