package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class IsLongerThan_BehaviorDescriptor extends IntervalCondition_BehaviorDescriptor {
  public IsLongerThan_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.IsLongerThan";
  }
}
