package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class IsShorterThan_BehaviorDescriptor extends IntervalCondition_BehaviorDescriptor {
  public IsShorterThan_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.IsShorterThan";
  }
}
