package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class IsShorterThanOrEqualTo_BehaviorDescriptor extends IntervalCondition_BehaviorDescriptor {
  public IsShorterThanOrEqualTo_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.IsShorterThanOrEqualTo";
  }
}
