package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class IsTheSameInstantAs_BehaviorDescriptor extends InstantOperators_BehaviorDescriptor {
  public IsTheSameInstantAs_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.IsTheSameInstantAs";
  }
}
