package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Minutes_BehaviorDescriptor extends TimeUnit_BehaviorDescriptor {
  public Minutes_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Minutes";
  }
}
