package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Months_BehaviorDescriptor extends TimeUnit_BehaviorDescriptor {
  public Months_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Months";
  }
}
