package GN.EN.DateTime.behavior;

/*Generated by MPS */

import GN.EN.behavior.Value_BehaviorDescriptor;

public class MonthValue_BehaviorDescriptor extends Value_BehaviorDescriptor {
  public MonthValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.MonthValue";
  }
}
