package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Now_BehaviorDescriptor extends Instant_BehaviorDescriptor {
  public Now_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Now";
  }
}
