package GN.EN.DateTime.behavior;

/*Generated by MPS */


public abstract class RelativeTimeConcept_BehaviorDescriptor extends DateTimeOperands_BehaviorDescriptor {
  public RelativeTimeConcept_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.RelativeTimeConcept";
  }
}
