package GN.EN.DateTime.behavior;

/*Generated by MPS */


public abstract class TemporalExpression_BehaviorDescriptor extends TimeCondition_BehaviorDescriptor {
  public TemporalExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.TemporalExpression";
  }
}
