package GN.EN.DateTime.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class TimeConcept_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TimeConcept_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.TimeConcept";
  }
}
