package GN.EN.DateTime.behavior;

/*Generated by MPS */

import GN.EN.behavior.Condition_BehaviorDescriptor;

public abstract class TimeCondition_BehaviorDescriptor extends Condition_BehaviorDescriptor {
  public TimeCondition_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.TimeCondition";
  }
}
