package GN.EN.DateTime.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Timing_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Timing_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Timing";
  }
}
