package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Tuesday_BehaviorDescriptor extends DayOfWeek_BehaviorDescriptor {
  public Tuesday_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Tuesday";
  }
}
