package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Wednesday_BehaviorDescriptor extends DayOfWeek_BehaviorDescriptor {
  public Wednesday_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Wednesday";
  }
}
