package GN.EN.DateTime.behavior;

/*Generated by MPS */


public class Years_BehaviorDescriptor extends TimeUnit_BehaviorDescriptor {
  public Years_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.DateTime.structure.Years";
  }
}
