package GN.Tabular;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.LanguageAspectDescriptor;
import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import GN.Tabular.editor.EditorAspectDescriptorImpl;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "cbcb9e45-b815-4592-9e58-c94e4fc84338(GN.Tabular)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "GN.Tabular";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("cbcb9e45-b815-4592-9e58-c94e4fc84338"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{"GN.EN"};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "54fda5aa-6969-4e1f-b2fa-7c49fc1cf25e(GN.Tabular#1348693278020054189)"));
  }
  @Override
  protected <T extends LanguageAspectDescriptor> T createAspectDescriptor(Class<T> descriptorClass) {
    if (descriptorClass == EditorAspectDescriptor.class) {
      return (T) new EditorAspectDescriptorImpl();
    }
    return super.createAspectDescriptor(descriptorClass);
  }
}
