package GN.EN.behavior;

/*Generated by MPS */


public class ActType_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public ActType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.ActType";
  }
}
