package GN.EN.behavior;

/*Generated by MPS */


public class Addition_BehaviorDescriptor extends CalculationExpression_BehaviorDescriptor {
  public Addition_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Addition";
  }
}
