package GN.EN.behavior;

/*Generated by MPS */


public class AdditionSubstractionRule_BehaviorDescriptor extends Rule_BehaviorDescriptor {
  public AdditionSubstractionRule_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.AdditionSubstractionRule";
  }
}
