package GN.EN.behavior;

/*Generated by MPS */


public abstract class CalculationExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public CalculationExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.CalculationExpression";
  }
}
