package GN.EN.behavior;

/*Generated by MPS */


public abstract class Comparision_BehaviorDescriptor extends Condition_BehaviorDescriptor {
  public Comparision_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Comparision";
  }
}
