package GN.EN.behavior;

/*Generated by MPS */


public class DerivationRule_BehaviorDescriptor extends Rule_BehaviorDescriptor {
  public DerivationRule_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.DerivationRule";
  }
}
