package GN.EN.behavior;

/*Generated by MPS */


public class DisabilityImmunity_BehaviorDescriptor extends Modaloperator_BehaviorDescriptor {
  public DisabilityImmunity_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.DisabilityImmunity";
  }
}
