package GN.EN.behavior;

/*Generated by MPS */


public class Divide_BehaviorDescriptor extends CalculationExpression_BehaviorDescriptor {
  public Divide_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Divide";
  }
}
