package GN.EN.behavior;

/*Generated by MPS */


public class DutyClaim_BehaviorDescriptor extends Modaloperator_BehaviorDescriptor {
  public DutyClaim_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.DutyClaim";
  }
}
