package GN.EN.behavior;

/*Generated by MPS */


public class Equation_BehaviorDescriptor extends Rule_BehaviorDescriptor {
  public Equation_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Equation";
  }
}
