package GN.EN.behavior;

/*Generated by MPS */


public class EventRule_BehaviorDescriptor extends Rule_BehaviorDescriptor {
  public EventRule_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.EventRule";
  }
}
