package GN.EN.behavior;

/*Generated by MPS */


public abstract class FactType_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public FactType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.FactType";
  }
}
