package GN.EN.behavior;

/*Generated by MPS */


public abstract class FactValue_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public FactValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.FactValue";
  }
}
