package GN.EN.behavior;

/*Generated by MPS */


public class FactCondition_BehaviorDescriptor extends Condition_BehaviorDescriptor {
  public FactCondition_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.FactCondition";
  }
}
