package GN.EN.behavior;

/*Generated by MPS */


public class FactRoleRef_BehaviorDescriptor extends FactValue_BehaviorDescriptor {
  public FactRoleRef_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.FactRoleRef";
  }
}
