package GN.EN.behavior;

/*Generated by MPS */


public class GNAmount_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNAmount_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNAmount";
  }
}
