package GN.EN.behavior;

/*Generated by MPS */


public class GNBoolean_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNBoolean_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNBoolean";
  }
}
