package GN.EN.behavior;

/*Generated by MPS */


public class GNDate_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNDate_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNDate";
  }
}
