package GN.EN.behavior;

/*Generated by MPS */


public class GNDateTime_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNDateTime_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNDateTime";
  }
}
