package GN.EN.behavior;

/*Generated by MPS */


public class GNDouble_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNDouble_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNDouble";
  }
}
