package GN.EN.behavior;

/*Generated by MPS */


public class GNInt_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNInt_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNInt";
  }
}
