package GN.EN.behavior;

/*Generated by MPS */


public class GNMonth_BehaviorDescriptor extends GNPeriod_BehaviorDescriptor {
  public GNMonth_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNMonth";
  }
}
