package GN.EN.behavior;

/*Generated by MPS */


public abstract class GNPeriod_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNPeriod_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNPeriod";
  }
}
