package GN.EN.behavior;

/*Generated by MPS */


public class GNString_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNString_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNString";
  }
}
