package GN.EN.behavior;

/*Generated by MPS */


public class GNVariable_BehaviorDescriptor extends GNType_BehaviorDescriptor {
  public GNVariable_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.GNVariable";
  }
}
