package GN.EN.behavior;

/*Generated by MPS */


public class ImmunityDisability_BehaviorDescriptor extends Modaloperator_BehaviorDescriptor {
  public ImmunityDisability_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.ImmunityDisability";
  }
}
