package GN.EN.behavior;

/*Generated by MPS */


public class IndividualNounConcept_BehaviorDescriptor extends Object_BehaviorDescriptor implements Thing_BehaviorDescriptor {
  public IndividualNounConcept_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.IndividualNounConcept";
  }
}
