package GN.EN.behavior;

/*Generated by MPS */


public class IndividualRole_BehaviorDescriptor extends RoleValue_BehaviorDescriptor {
  public IndividualRole_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.IndividualRole";
  }
}
