package GN.EN.behavior;

/*Generated by MPS */


public class IndividualRoleRef_BehaviorDescriptor extends RoleValue_BehaviorDescriptor {
  public IndividualRoleRef_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.IndividualRoleRef";
  }
}
