package GN.EN.behavior;

/*Generated by MPS */


public class InstantAct_BehaviorDescriptor extends TypeOfAct_BehaviorDescriptor {
  public InstantAct_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.InstantAct";
  }
}
