package GN.EN.behavior;

/*Generated by MPS */


public class IntegerValue_BehaviorDescriptor extends Value_BehaviorDescriptor {
  public IntegerValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.IntegerValue";
  }
}
