package GN.EN.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class InteractionContext_BehaviorDescriptor extends Context_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public InteractionContext_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.InteractionContext";
  }
}
