package GN.EN.behavior;

/*Generated by MPS */


public class IsIndividualOf_BehaviorDescriptor extends Rule_BehaviorDescriptor {
  public IsIndividualOf_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.IsIndividualOf";
  }
}
