package GN.EN.behavior;

/*Generated by MPS */


public class LargerThan_BehaviorDescriptor extends Comparision_BehaviorDescriptor {
  public LargerThan_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.LargerThan";
  }
}
