package GN.EN.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class LegalContext_BehaviorDescriptor extends Context_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public LegalContext_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.LegalContext";
  }
}
