package GN.EN.behavior;

/*Generated by MPS */


public class LiabilityPower_BehaviorDescriptor extends Modaloperator_BehaviorDescriptor {
  public LiabilityPower_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.LiabilityPower";
  }
}
