package GN.EN.behavior;

/*Generated by MPS */


public class N_Ary_FactType_BehaviorDescriptor extends FactType_BehaviorDescriptor {
  public N_Ary_FactType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.N_Ary_FactType";
  }
}
