package GN.EN.behavior;

/*Generated by MPS */


public class NoRightPrivilege_BehaviorDescriptor extends Modaloperator_BehaviorDescriptor {
  public NoRightPrivilege_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.NoRightPrivilege";
  }
}
