package GN.EN.behavior;

/*Generated by MPS */


public class Norm_BehaviorDescriptor extends Rule_BehaviorDescriptor {
  public Norm_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Norm";
  }
}
