package GN.EN.behavior;

/*Generated by MPS */


public class Object_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public Object_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Object";
  }
}
