package GN.EN.behavior;

/*Generated by MPS */


public class ObjectRole_BehaviorDescriptor extends Role_BehaviorDescriptor {
  public ObjectRole_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.ObjectRole";
  }
}
