package GN.EN.behavior;

/*Generated by MPS */


public class ParameterTable_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public ParameterTable_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.ParameterTable";
  }
}
