package GN.EN.behavior;

/*Generated by MPS */


public class Proposition_BehaviorDescriptor extends Concept_BehaviorDescriptor {
  public Proposition_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Proposition";
  }
}
