package GN.EN.behavior;

/*Generated by MPS */


public class RelationExists_BehaviorDescriptor extends Condition_BehaviorDescriptor {
  public RelationExists_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.RelationExists";
  }
}
