package GN.EN.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Role_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Role_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Role";
  }
}
