package GN.EN.behavior;

/*Generated by MPS */


public class SmallerThan_BehaviorDescriptor extends Comparision_BehaviorDescriptor {
  public SmallerThan_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.SmallerThan";
  }
}
