package GN.EN.behavior;

/*Generated by MPS */


public class SpecialisationRule_BehaviorDescriptor extends Rule_BehaviorDescriptor {
  public SpecialisationRule_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.SpecialisationRule";
  }
}
