package GN.EN.behavior;

/*Generated by MPS */


public class StringValue_BehaviorDescriptor extends Value_BehaviorDescriptor {
  public StringValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.StringValue";
  }
}
