package GN.EN.behavior;

/*Generated by MPS */


public class Substraction_BehaviorDescriptor extends CalculationExpression_BehaviorDescriptor {
  public Substraction_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.Substraction";
  }
}
