package GN.EN.behavior;

/*Generated by MPS */


public class UniqueConstraint_BehaviorDescriptor extends Rule_BehaviorDescriptor {
  public UniqueConstraint_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.UniqueConstraint";
  }
}
