package GN.EN.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class VariableDefinition_BehaviorDescriptor extends Concept_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public VariableDefinition_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.VariableDefinition";
  }
}
