package GN.EN.behavior;

/*Generated by MPS */


public class VariableReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public VariableReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "GN.EN.structure.VariableReference";
  }
}
